//Fecha:  jueves 30 Octubre 2025 
//Autor: Ana Roncal 

#ifndef ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H
#define ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H
struct ElementoArbolBinarioBusqueda {
    int numero;
};
#endif //ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H